import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable'; // CORRECTED IMPORT

interface InvoiceItem {
  id: string;
  description: string;
  quantity: number;
  unitPrice: number;
  total: number;
}

interface Invoice {
  invoiceNumber: string;
  vendor: string;
  vendorAddress: string;
  vendorTaxId: string;
  client: string;
  clientAddress: string;
  clientEmail: string;
  date: string;
  dueDate: string;
  items: InvoiceItem[];
  subtotal: number;
  tax: number;
  total: number;
}

export const generatePDF = (invoice: Invoice): Promise<void> => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new jsPDF();

      // Add header with company branding
      doc.setFontSize(24);
      doc.setTextColor(37, 99, 235); // #2563eb
      doc.text('My E-lnvoice', 20, 20);

      doc.setFontSize(20);
      doc.setTextColor(40, 40, 40);
      doc.text('INVOICE', 20, 35);

      // Invoice details
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text(`Invoice Number: ${invoice.invoiceNumber}`, 20, 45);
      doc.text(`Issue Date: ${invoice.date}`, 20, 51);
      doc.text(`Due Date: ${invoice.dueDate}`, 20, 57);

      // Draw separator line
      doc.setDrawColor(226, 232, 240);
      doc.setLineWidth(0.5);
      doc.line(20, 62, 190, 62);

      // Vendor and Client information
      doc.setFontSize(12);
      doc.setTextColor(40, 40, 40);
      doc.text('From:', 20, 75);
      doc.text('Bill To:', 120, 75);

      doc.setFontSize(10);
      doc.setTextColor(80, 80, 80);

      // Vendor details
      const vendorLines = doc.splitTextToSize(invoice.vendor, 80);
      doc.text(vendorLines, 20, 82);
      const vendorAddressLines = doc.splitTextToSize(invoice.vendorAddress, 80);
      doc.text(vendorAddressLines, 20, 82 + (vendorLines.length * 5));
      doc.text(`Tax ID: ${invoice.vendorTaxId}`, 20, 82 + (vendorLines.length * 5) + (vendorAddressLines.length * 5));

      // Client details
      const clientLines = doc.splitTextToSize(invoice.client, 80);
      doc.text(clientLines, 120, 82);
      const clientAddressLines = doc.splitTextToSize(invoice.clientAddress, 80);
      doc.text(clientAddressLines, 120, 82 + (clientLines.length * 5));
      doc.text(invoice.clientEmail, 120, 82 + (clientLines.length * 5) + (clientAddressLines.length * 5));

      // Line items table
      const tableColumn = ["Description", "Qty", "Unit Price", "Total"];
      const tableRows = invoice.items.map(item => [
        item.description,
        item.quantity.toString(),
        `$${item.unitPrice.toFixed(2)}`,
        `$${item.total.toFixed(2)}`
      ]);

      // CORRECTED FUNCTION CALL
      autoTable(doc, {
        startY: 120,
        head: [tableColumn],
        body: tableRows,
        theme: 'striped',
        // ... other styles
        // ADJUST THE WIDTHS BELOW
        columnStyles: {
          0: { cellWidth: 88 }, // Description column (was 90)
          1: { cellWidth: 20 }, // Quantity column (was 25)
          2: { cellWidth: 32 }, // Unit Price column (was 35)
          3: { cellWidth: 30 }  // Total column (was 35)
        }
      });

      // Totals section
      const finalY = (doc as any).lastAutoTable.finalY + 15;

      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text('Subtotal:', 140, finalY);
      doc.text(`$${invoice.subtotal.toFixed(2)}`, 185, finalY, { align: 'right' });

      doc.text('Tax (10%):', 140, finalY + 7);
      doc.text(`$${invoice.tax.toFixed(2)}`, 185, finalY + 7, { align: 'right' });

      // Draw line before total
      doc.setDrawColor(226, 232, 240);
      doc.line(140, finalY + 11, 185, finalY + 11);

      doc.setFontSize(12);
      doc.setTextColor(40, 40, 40);
      doc.text('Total:', 140, finalY + 20);
      doc.text(`$${invoice.total.toFixed(2)}`, 185, finalY + 20, { align: 'right' });

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text('Thank you for your business!', 105, 280, { align: 'center' });
      doc.text('Generated by My E-lnvoice - AI-Powered Invoicing', 105, 285, { align: 'center' });

      // Save the PDF
      doc.save(`invoice-${invoice.invoiceNumber}.pdf`);
      const pdfDataUri = doc.output('datauristring');
      window.open(pdfDataUri);
      resolve();
    } catch (error) {
      console.error('PDF generation error:', error);
      reject(error);
    }
  });
};